language: go
go:
  - "1.10"
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get github.com/mattn/goveralls
services:
  - postgresql
script:
  - go test -v -coverpkg ./... -coverprofile=coverage.out ./...
  - goveralls -service=travis-ci -coverprofile=coverage.out
  
